"""vertical slice schema

Revision ID: 0001_vertical_slice
Revises: 
Create Date: 2026-07-20 14:59:48.197585
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_vertical_slice'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'user'"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("role IN ('user','account_admin')", name='ck_rag_user_role'),
    sa.CheckConstraint("status IN ('active','disabled','deleting')", name='ck_rag_user_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('rag_knowledge_base',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('chunk_size', sa.Integer(), server_default=sa.text('512'), nullable=False),
    sa.Column('overlap', sa.Integer(), server_default=sa.text('50'), nullable=False),
    sa.Column('embedding_model', sa.String(length=200), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('active_collection', sa.String(length=200), nullable=False),
    sa.Column('index_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('index_status', sa.String(length=20), server_default=sa.text("'ready'"), nullable=False),
    sa.Column('similarity_threshold', sa.Numeric(precision=3, scale=2), server_default=sa.text('0.20'), nullable=False),
    sa.Column('top_k', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("index_status IN ('ready','rebuilding','failed','deleting')", name='ck_rag_kb_index_status'),
    sa.CheckConstraint('chunk_size >= 64', name='ck_rag_kb_chunk_size'),
    sa.CheckConstraint('overlap >= 0 AND overlap < chunk_size', name='ck_rag_kb_overlap'),
    sa.CheckConstraint('top_k >= 1', name='ck_rag_kb_top_k'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['rag_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'owner_user_id', name='uk_kb_owner')
    )
    op.create_index('idx_kb_owner', 'rag_knowledge_base', ['owner_user_id', 'updated_at'], unique=False)
    op.create_table('rag_session',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['rag_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_session_expiry', 'rag_session', ['expires_at'], unique=False)
    op.create_index('idx_session_user_expiry', 'rag_session', ['user_id', 'expires_at'], unique=False)
    op.create_table('rag_conversation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('kb_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id', 'owner_user_id'], ['rag_knowledge_base.id', 'rag_knowledge_base.owner_user_id'], name='fk_conversation_kb_owner', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'owner_user_id', name='uk_conversation_owner')
    )
    op.create_index('idx_conversation_owner', 'rag_conversation', ['owner_user_id', 'updated_at'], unique=False)
    op.create_table('rag_document',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=2000), nullable=False),
    sa.Column('source_type', sa.String(length=50), server_default=sa.text("'upload'"), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('tags', sa.String(length=2000), nullable=True),
    sa.Column('chunk_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status IN ('pending','running','done','failed','deleting')", name='ck_rag_document_status'),
    sa.CheckConstraint('chunk_count >= 0', name='ck_rag_document_chunk_count'),
    sa.ForeignKeyConstraint(['kb_id', 'owner_user_id'], ['rag_knowledge_base.id', 'rag_knowledge_base.owner_user_id'], name='fk_document_kb_owner', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'owner_user_id', name='uk_document_owner')
    )
    op.create_index('idx_document_kb_status', 'rag_document', ['kb_id', 'status'], unique=False)
    op.create_index('idx_document_owner', 'rag_document', ['owner_user_id'], unique=False)
    op.create_table('rag_document_job',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('kb_job_id', sa.BigInteger(), nullable=True),
    sa.Column('target_collection', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("job_type IN ('ingest','delete')", name='ck_rag_document_job_type'),
    sa.CheckConstraint("stage IS NULL OR stage IN ('parsing','chunking','embedding','indexing')", name='ck_rag_document_job_stage'),
    sa.CheckConstraint("status IN ('pending','running','done','failed')", name='ck_rag_document_job_status'),
    sa.CheckConstraint('attempts >= 0', name='ck_rag_document_job_attempts'),
    sa.ForeignKeyConstraint(['doc_id', 'owner_user_id'], ['rag_document.id', 'rag_document.owner_user_id'], name='fk_document_job_owner', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_job_claim', 'rag_document_job', ['status', 'created_at'], unique=False)
    op.create_index('idx_document_job_document', 'rag_document_job', ['doc_id'], unique=False)
    op.create_index('idx_document_job_owner', 'rag_document_job', ['owner_user_id'], unique=False)
    op.create_table('rag_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'completed'"), nullable=False),
    sa.Column('retry_of_message_id', sa.BigInteger(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant','system')", name='ck_rag_message_role'),
    sa.CheckConstraint("status IN ('streaming','completed','failed')", name='ck_rag_message_status'),
    sa.CheckConstraint('sequence >= 0', name='ck_rag_message_sequence'),
    sa.CheckConstraint('tokens_used >= 0', name='ck_rag_message_tokens'),
    sa.ForeignKeyConstraint(['conversation_id'], ['rag_conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retry_of_message_id'], ['rag_message.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'sequence', name='uk_conversation_sequence')
    )
    op.create_table('rag_query_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('kb_id', sa.BigInteger(), nullable=False),
    sa.Column('user_message_id', sa.BigInteger(), nullable=False),
    sa.Column('assistant_message_id', sa.BigInteger(), nullable=True),
    sa.Column('chunks_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('result_status', sa.String(length=20), nullable=True),
    sa.Column('tokens_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("result_status IS NULL OR result_status IN ('success','empty','error')", name='ck_rag_query_result'),
    sa.CheckConstraint('chunks_count >= 0', name='ck_rag_query_chunks'),
    sa.CheckConstraint('tokens_used >= 0', name='ck_rag_query_tokens'),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['rag_message.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['rag_conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kb_id', 'owner_user_id'], ['rag_knowledge_base.id', 'rag_knowledge_base.owner_user_id'], name='fk_query_kb_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_message_id'], ['rag_message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_query_conversation', 'rag_query_log', ['conversation_id'], unique=False)
    op.create_index('idx_query_owner_time', 'rag_query_log', ['owner_user_id', 'created_at'], unique=False)
    op.create_index('idx_query_result', 'rag_query_log', ['result_status', 'created_at'], unique=False)
    op.create_table('rag_reference',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_id', sa.String(length=160), nullable=True),
    sa.Column('doc_id', sa.BigInteger(), nullable=True),
    sa.Column('doc_title', sa.String(length=500), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['rag_message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reference_message', 'rag_reference', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reference_message', table_name='rag_reference')
    op.drop_table('rag_reference')
    op.drop_index('idx_query_result', table_name='rag_query_log')
    op.drop_index('idx_query_owner_time', table_name='rag_query_log')
    op.drop_index('idx_query_conversation', table_name='rag_query_log')
    op.drop_table('rag_query_log')
    op.drop_table('rag_message')
    op.drop_index('idx_document_job_owner', table_name='rag_document_job')
    op.drop_index('idx_document_job_document', table_name='rag_document_job')
    op.drop_index('idx_document_job_claim', table_name='rag_document_job')
    op.drop_table('rag_document_job')
    op.drop_index('idx_document_owner', table_name='rag_document')
    op.drop_index('idx_document_kb_status', table_name='rag_document')
    op.drop_table('rag_document')
    op.drop_index('idx_conversation_owner', table_name='rag_conversation')
    op.drop_table('rag_conversation')
    op.drop_index('idx_session_user_expiry', table_name='rag_session')
    op.drop_index('idx_session_expiry', table_name='rag_session')
    op.drop_table('rag_session')
    op.drop_index('idx_kb_owner', table_name='rag_knowledge_base')
    op.drop_table('rag_knowledge_base')
    op.drop_table('rag_user')
    # ### end Alembic commands ###

